const YemenCities = [
    "Sana'a",
    "Aden",
    "Taiz",
    "Al Hudaydah",
    "Ibb",
    "Dhamar",
    "Al-Mukalla",
    "Hajjah",
    "Saywun",
    "Amran",
    "Zabid",
    "Bajil",
    "Sadah",
    "Lahij",
    "Bayt al-Faqih",
    "Sa'dah",
    "Al Ghaydah",
    "Ma'rib",
    "Al Mukalla",
    "Al Hazm",
    "Al Bayda",
    "Al Kowd",
    "Al Jawf",
    "Hodeidah",
    "Dhamār",
    "Ibb",
    "Raymah",
    "Mukayras",
    "Al Anad",
    "Ash Shihr",
    "Zinjibar",
];

export default YemenCities;
